@startuml Diagrama de Despliegue
title Diagrama de Despliegue - Plataforma Digital UCV

node "Usuarios" {
    actor "Estudiantes"
    actor "Profesores"
    actor "Personal Administrativo"
}


node "Dispositivos de Usuario" {
    node "Aplicación de Escritorio" {
        artifact "PlataformaVirtual.jar"
        database "Base de Datos"
    }
}

"Usuarios" -- "Aplicación de Escritorio"

"PlataformaVirtual.jar" -- "Base de Datos"
@enduml