@startuml Diagrama de Despliegue
title Diagrama de Despliegue - Plataforma Digital UCV

node "Usuarios" {
    actor "Estudiantes"
    actor "Profesores"
    actor "Personal Administrativo"
}


node "Dispositivos de Usuario" {
    node "Aplicación de Escritorio" {
        artifact "PlataformaVirtual.jar"
    }
    database "Base de Datos"
}

"Estudiantes" -- "Aplicación de Escritorio"
"Profesores" -- "Aplicación de Escritorio"
"Personal Administrativo" -- "Aplicación de Escritorio"

"Aplicación de Escritorio" -- "Base de Datos"
@enduml